# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_broker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_broker.proto\x12\x0emessage_broker\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0fPublishResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"$\n\x11SubscribeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x19ValidateConnectionRequest\",\n\x1aValidateConnectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9c\x02\n\rMessageBroker\x12J\n\x07Publish\x12\x1e.message_broker.PublishRequest\x1a\x1f.message_broker.PublishResponse\x12R\n\tSubscribe\x12 .message_broker.SubscribeRequest\x1a!.message_broker.SubscribeResponse0\x01\x12k\n\x12ValidateConnection\x12).message_broker.ValidateConnectionRequest\x1a*.message_broker.ValidateConnectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=40
  _globals['_PUBLISHREQUEST']._serialized_end=88
  _globals['_PUBLISHRESPONSE']._serialized_start=90
  _globals['_PUBLISHRESPONSE']._serialized_end=123
  _globals['_SUBSCRIBEREQUEST']._serialized_start=125
  _globals['_SUBSCRIBEREQUEST']._serialized_end=158
  _globals['_SUBSCRIBERESPONSE']._serialized_start=160
  _globals['_SUBSCRIBERESPONSE']._serialized_end=196
  _globals['_VALIDATECONNECTIONREQUEST']._serialized_start=198
  _globals['_VALIDATECONNECTIONREQUEST']._serialized_end=225
  _globals['_VALIDATECONNECTIONRESPONSE']._serialized_start=227
  _globals['_VALIDATECONNECTIONRESPONSE']._serialized_end=271
  _globals['_MESSAGEBROKER']._serialized_start=274
  _globals['_MESSAGEBROKER']._serialized_end=558
# @@protoc_insertion_point(module_scope)
